valor1 = input("Digite o primeiro valor: ")
valor2 = input("Digite o segundo valor: ")
soma = int(valor1) + int(valor2)
print("A soma entre {}".format(valor1), "e {} ".format(valor2), "é igual: {}".format(soma))
sub = int(valor1) - int(valor2)
print("A subtração de {}".format(valor1), "menos {}".format(valor2), "é igual: {}".format(sub))
mult = int(valor1) * int(valor2)
print("A multiplicação de {}".format(valor1), "por {}".format(valor2), "é igual: {}".format(mult))
div = int(valor1) / int(valor2)
print("A divisão de {}".format(valor1), "por {}".format(valor2), "é igual: {}".format(div))
